### ISSUE TITLE
Add helmutils fork

### ISSUE THREAD

**Issue by ichbinfrog** [ichbinfrog/helmutils#2]
Features:
- Allows for forking values files with different intents (production, staging, test, etc.). Sync up same values and obfuscate some others (replace with {}).
- Configurable with another yaml file. For example:

_values.yaml
```yaml
map1:
  key1: value1
  map2:
    key2: value2
key3: value3
```
_production_values.yaml
```yaml
@ignore key1
@ignore map2

key3: value3
```
```
_release_values.yaml
```yaml
@ignore key1
```
